[package]
name = "rumose"
version = "0.1.0"
authors = ["Luís Silva <lfssilva@ua.pt>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
tiny_http = "0.8"